import { GlobalStore } from './GlobalStore';
import { DevicesCollection } from './DevicesCollection';
import { GroupsCollection } from './GroupsCollection';
import { StageMembersCollection } from './StageMembersCollection';
import { StagesCollection } from './StagesCollection';
import { UsersCollection } from './UsersCollection';
import { RemoteVideoProducersCollection } from './RemoteVideoProducersCollection';
import { RemoteAudioProducersCollection } from './RemoteAudioProducersCollection';
import { LocalConsumersCollection } from './LocalConsumersCollection';
import { SoundCardCollection } from './SoundCardCollection';
import { ChatMessages } from './ChatMessages';
import {RemoteOvTrackCollection} from "./RemoteOvTrackCollection";
import {OvTrackCollection} from "./OvTrackCollection";
import {CustomGroupVolumeCollection} from "./CustomGroupVolumeCollection";
import {CustomStageMemberVolumeCollection} from "./CustomStageMemberVolumeCollection";
import {CustomRemoteAudioProducerVolumeCollection} from "./CustomRemoteAudioProducerVolumeCollection";
import {CustomRemoteAudioProducerPositionCollection} from "./CustomRemoteAudioProducerPositionCollection";
import {CustomGroupPositionCollection} from "./CustomGroupPositionCollection";
import {CustomStageMemberPositionCollection} from "./CustomStageMemberPositionCollection";
import {CustomRemoteOvTrackPositionCollection} from "./CustomRemoteOvTrackPositionCollection";
import {CustomRemoteOvTrackVolumeCollection} from "./CustomRemoteOvTrackVolumeCollection";

export interface RootReducer {
  global: GlobalStore;
  devices: DevicesCollection;
  users: UsersCollection;
  stages: StagesCollection;
  groups: GroupsCollection;
  customGroupVolumes: CustomGroupVolumeCollection;
  customGroupPositions: CustomGroupPositionCollection;
  stageMembers: StageMembersCollection;
  customStageMemberVolumes: CustomStageMemberVolumeCollection;
  customStageMemberPositions: CustomStageMemberPositionCollection;
  videoProducers: RemoteVideoProducersCollection;
  audioProducers: RemoteAudioProducersCollection;
  customRemoteAudioProducerVolumes: CustomRemoteAudioProducerVolumeCollection;
  customRemoteAudioProducerPositions: CustomRemoteAudioProducerPositionCollection;
  videoConsumers: LocalConsumersCollection;
  audioConsumers: LocalConsumersCollection;
  ovTracks: OvTrackCollection;
  remoteOvTracks: RemoteOvTrackCollection;
  customRemoteOvTrackVolumes: CustomRemoteOvTrackVolumeCollection;
  customRemoteOvTrackPositions: CustomRemoteOvTrackPositionCollection;
  soundCards: SoundCardCollection;
  chatMessages: ChatMessages;
}
